var GAME_LEVELS = [
  ["                                                                                ",
   "                        o                                             o         ",
   "                                                                                ",
   "                                                                                ",
   "     o              x  xxx  x                                                   ",
   "                     xx!!!xx                                         xxxx       ",
   "        xx       xxxx!!!!!!!xxxx          o                   x                 ",
   "                     xx!!!xx                                  x                 ",
   "                    x  xvx  x                                 x                 ",
   "    xx                                x  xxx  x               xxx               ",
   "                                       xx!!!xx                   x              ",
   "                                    xxx!!!!!!!xxx                           xx  ",
   "  xx    xx                             xx!!!xx                               x  ",
   "  x                                   x  xvx  x                       xx     x  ",
   "  x           @                                                              x  ",
   "  x         xxxxx                                    xxx                     x  ",
   "  x!!!!!!!!!x   x                                      xxxxx     xxxxx!!!!!!!x  ",
   "  xxxxxxxxxxx   xxxxxxxx                                   xxxxxxx   xxxxxxxxx  ",
   "                       x                                   x                    ",
   "                       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                    xxxxxxx                                                   ",
   "                                                          x                                                   ",
   "                                                          x                                                   ",
   "                  x                                 xx    x                                                   ",
   "                  |                                  xo   x                xxxxxxxxxxx                        ",
   "                                                     x    x          xxxxxx           xxxxxx                  ",
   "                                                    xx    x         x                       xxx               ",
   "                                                     x   ox        x        xxxxxxxxx          x              ",
   "                                    x                x    x       x       xx         xx    o    x             ",
   "                 xx                 |               xx    x       x      x     o       x        x             ",
   "                  x                                  x o  x       x=     x             x=       x             ",
   "                  x                                  x    x       x      xxx   x       x        x             ",
   "                 xx                                 xx    x        x        xx         x   x    x             ",
   "                  x                                  x    x         xx                x         x             ",
   "                  x                                  x    x           xxxx          xx         x              ",
   "                 xx                        o        xx    x               xxxxxxxxxx       xxxx               ",
   "           o                        x                x    x                             xxx                   ",
   "                             x                       x       o                        xx                      ",
   "          xx                                        xx                 xxxxxxxxxxxxxxx                        ",
   "        xxx                                   p      x    xxx      xxxx                                       ",
   "=   @ xxx                                     x      x    x                                                   ",
   "xxxxxxx                                              x    x                                                   ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                            ",
   "                                                                       o    ",
   "                                                                            ",
   "                                                                            ",
   "                                                                            ",
   "                                                               xxxxxx       ",
   "                                                                            ",
   "                                                        x                   ",
   "                                                  o                         ",
   "                                                                            ",
   "                                                  x                         ",
   "                                                   x                        ",
   "                                                                            ",
   "                                                          x      o          ",
   "                                                                            ",
   "                                                                 xx         ",
   "                                                                  x         ",
   "                                                                  x         ",
   "                                                                 xx         ",
   "                                                          x                 ",
   "                                    o                                       ",
   "                                                   x                        ",
   "                                    x       x                               ",
   "                             x      x       x                               ",
   "                             x      x       x                               ",
   "                       x     x                                              ",
   "                       x                                                    ",
   "                       x                                                    ",
   "             x   x                                                          ",
   "              x x                                                           ",
   "        p      x                                                            ",
   "    x   x                                                                   ",
   "     x@x                                                                    ",
   "      x                                                                     ",
   "                                                                            ",
   "                                                                            ",
   "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "                                                                            ",
   "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"],
  ["                 ",
   " x   x  xx  x  x ",
   "  x x  x  x x  x ",
   "   x   x  x x  x ",
   "   x   x  x x  x ",
   "   x    xx   xx  ",
   "                 ",
   " x   x xxx x   x ",
   " x   x  x  xx  x ",
   " x x x  x  x x x ",
   " x x x  x  x  xx ",
   "  x x  xxx x   x ",
   "                 "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
